on: ["push", "pull_request"]

name: Test Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install npm dependencies
        run: npm install # switch to `npm ci` when Node.js 6 support is dropped

      - name: Install c8
        run: npm i c8 -g

      - name: Run tests
        if: always()
        run: c8 --exclude  "lib-to-test/src/isArguments.js" --exclude "lib-to-test/src/isArrayLike.js" --exclude "lib-to-test/src/isBuffer.js" --exclude "lib-to-test/src/isLength.js" --exclude "lib-to-test/src/isObject.js" --exclude "lib-to-test/src/isObjectLike.js" --exclude "lib-to-test/src/isSymbol.js" --exclude "lib-to-test/src/isTypedArray.js" --exclude "lib-to-test/src/memoize.js" --exclude "lib-to-test/src/slice.js" --exclude "lib-to-test/src/toFinite.js" --exclude "lib-to-test/src/toInteger.js" --reporter=lcov npm test

      - name: Coveralls
        if: always()
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: ${{matrix.os}}-node-${{ matrix.node }}
          path-to-lcov: ./coverage/lcov.info
          #parallel: true

  finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/lcov.info
          #parallel-finished: true
